const ENDPOINT_ROOT = '/';
const SURVEYS_ENDPOINT = 'surveys';

export const POST_LOGIN = `${ENDPOINT_ROOT}auth`;
export const GET_PROFILE = `${ENDPOINT_ROOT}profile`;
export const GET_SURVEYS = `${ENDPOINT_ROOT}${SURVEYS_ENDPOINT}`;
export const GET_SURVEY_BY_ID = `${ENDPOINT_ROOT}${SURVEYS_ENDPOINT}`;
export const PUT_SURVEY_STATUS = `${ENDPOINT_ROOT}${SURVEYS_ENDPOINT}`;
export const POST_SURVEY_RESULTS = `${ENDPOINT_ROOT}${SURVEYS_ENDPOINT}`;
export const GET_SURVEY_CHART_RESULTS = `${ENDPOINT_ROOT}${SURVEYS_ENDPOINT}/results`;
